### ISSUE TITLE
Public methods to access from context

### ISSUE THREAD

**Issue by avishayil** [tuantle/react-native-search-header#1]
Hello @tuantle , Thanks for the great component.
I was wondering if it would be possible to create public methods for showing and hiding the search header, in order to make the search header accessible from context.
Something like this:
https://github.com/root-two/react-native-drawer#opening--closing-the-drawer-programmatically

Thanks!

**Comment by tuantle** [comment]
Hi avishayil,
 I can expose the minimize/maximize methods via refs like this example:
```js
    onOpenSearchHeader () {
        this.refs.searchHeader.maximize();
    }
    render () {
        return (
            <View style = { styles.container }>
                <StatusBar barStyle = 'light-content' />
                <View style = { styles.status }/>
                <View style = { styles.header }>
                    <Text style = { styles.label }>Demo</Text>
                </View>
                <SearchHeader
                    ref = 'searchHeader'
                    statusBarHeightOffet = { 21 }
                />
                <View style = { styles.button }>
                    <Button
                        title = 'Open Search'
                        color = '#f5fcff'
                        onPress = { this.onOpenSearchHeader }
                    />
                </View>
            </View>
        );
    }
```

**Comment by avishayil** [comment]
Exactly! Waiting for this to be implemented.

**Comment by tuantle** [comment]
Ok I just updated to new version.

Added 3 methods that you can access via React "ref".

doShowSearch	                Call to show the SearchHeader.
doHideSearch	                Call to hide the SearchHeader.
doClearSearchSuggestion	Call to clear search suggestion list.

**Comment by avishayil** [comment]
Awesome! I'll try it and let you know how it works.
Thanks!
