### ISSUE TITLE
Integration with react-native-router-flux

### ISSUE THREAD

**Issue by avishayil** [tuantle/react-native-search-header#2]
Hello @tuantle ,
I wanted to see how can we integrate this component with RNRF:
https://github.com/aksonov/react-native-router-flux
The intension is to render the search component, so it would be available from any scene.
I'm currently using the implementation like this:
```javascript
            <View style={{flex: 1}}>
            <SearchHeader
                ref = {(searchHeader) => {
                    this.searchHeader = searchHeader;
                }}
                statusHeightOffet = { 21 }
            />
                <Router>
                // Start rendering scenes
```

Then on `componentDidMount`:
```javascript
        this.searchHeader.doShowSearch();
```

The problem is that the `react-native-router-flux` navBar is not usable after finishing search, because apparently the search bar is still "there", even though it's not visible.

Any advice?

**Comment by tuantle** [comment]
The search header is still there, is it just invisible because I only transition the opacity during animation. I will get this fixed and will update soon.

**Comment by avishayil** [comment]
Awesome!

**Comment by tuantle** [comment]
New view 0.1.3 just updated with the fix for this issue. 

Some methods and properties were renamed. You can check read me.
