### ISSUE TITLE
Facing an alignment issue in suggestions 

### ISSUE THREAD

**Issue by tushgup** [tuantle/react-native-search-header#24]
Hey! Thank you for making this amazing component, it's exactly what I needed.

I replaced your Google Auto Suggest fetch URL with a different API, but it generates the same sort of results. I think the issue is that my response has longer text, sometimes even two lines.. any idea how I can fix the alignment here? Maybe putting a numberofLines=1 to truncate it somewhere?

![screen shot 2018-08-28 at 9 08 37 pm](https://user-images.githubusercontent.com/5716459/44734398-70c6d600-ab07-11e8-9d99-cd0895584f5d.png)

Thanks so much.

**Comment by tuantle** [comment]
Hi, the search result texts are render by the Text component at line 1012

`<Text style = { adjustedStyle.suggestionEntry }>{ entry.value }</Text>`

To improve the styling when you have too many words to display in a single line is to truncate the end with "..."

Can you add a this prop ellipsizeMode = 'tail'

`<Text
     ellipsizeMode = 'tail'
     style = { adjustedStyle.suggestionEntry }
>{ entry.value }</Text>`

Let me know if that fix your issue.

**Comment by tushgup** [comment]
Thank you for the quick reply! I did add the prop, but it still seems to persist. 

By the way, if you want to recreate this issue, please query this API: http://completion.amazon.com/search/complete?search-alias=aps&client=amazon-search-ui&mkt=1&q=${text}

![screen shot 2018-08-28 at 11 04 42 pm](https://user-images.githubusercontent.com/5716459/44739969-d8385200-ab16-11e8-980b-f353633668bb.png)

**Comment by tuantle** [comment]
Ok I'll try and fix this in a day or two and let you know. Also are you using react native 0.56?

**Comment by tushgup** [comment]
Umm, forgive me because I'm new to RN, but I'm using Expo. 

My package.json says I'm on Expo 29.0.0

Is that enough information? Please let me know! 👍

**Comment by tuantle** [comment]
Updated to new version 0.2.8. It should fixed the above styling issue.

**Comment by tuantle** [comment]
Use the onHide callback of this component. Something like this.

```
<SearchHeader
    onHide = {() => {
        const {
         navigation
        } = this.props;
        navigation.goBack();
    }
/>
```

**Comment by tushgup** [comment]
Ah! I had tried something similar, but this worked! Thanks so much for all your help. Closing the issue now :)
