### ISSUE TITLE
Laggy TextInput while typing

### ISSUE THREAD

**Issue by tushgup** [tuantle/react-native-search-header#25]
I think there's some issue with the component's text input field - while typing a query, I think because of the async autosuggestions, it eats a few letters from the query. 

For example, searching for "iPhone X" turned into "iphoex", "Apple iPhone" into "Ape pow" etc.
I noticed this in your example code as well. Any help will be greatly appreciated!

![searchheaderbuggif](https://user-images.githubusercontent.com/5716459/45275645-747d3400-b4db-11e8-83bc-172ad83bbd88.gif)

**Comment by biocross** [comment]
+1 This only happens when async suggestions are enabled, otherwise it works just fine. More severe on Android, compared to iOS.

**Comment by tuantle** [comment]
Hmm.. weird. Ok, I will take a look at the lag issue. I never notice it before while testing.

**Comment by tuantle** [comment]
Ok found and fixed the issue. I moved the text input related state update outside of the async suggestion call. Shouldn't be in there in the first place. Thanks for spotting the bug. I will push out new version later today.

**Comment by tushgup** [comment]
Works great on 0.2.9. Thanks for the prompt fix!
