### ISSUE TITLE
Allow overwrite  input fontSize

### ISSUE THREAD

**Issue by shiftrtech** [tuantle/react-native-search-header#28]
I can't overwrite input `fontSize` style property:

`style={{
                  input: { 
                    fontFamily: 'Roboto-Thin', 
                    fontWeight: 'normal', 
                    fontSize: 12, //<-- This doesn't works
                    textAlign: 'left',
                  }
                }}`

Any tip?

**Comment by tuantle** [comment]
Hi i am a bit busy at the moment to check on this, but will do as soon as i can.

**Comment by tuantle** [comment]
Took a while but this should be fixed.
