### ISSUE TITLE
After dismiss warning, app is not responsive anymore

### ISSUE THREAD

**Issue by avishayil** [tuantle/react-native-search-header#3]
Don't know if it's library specific or RN problem, but I noticed that if I dismiss the warning on `ref`, app does not respond anymore. (Android)

GIF:
![error](https://i.imgur.com/ZJ8iXux.gif "error")

**Comment by tuantle** [comment]
I tested this component with react native 0.40. I will resolve the ref warning for the next version update.

**Comment by tuantle** [comment]
Fixed "ref" warning with new version 0.1.4. 
I also added new prop "entryAnimation" option. See ReadMe.

**Comment by tuantle** [comment]
Did the update resolve your issue? Can I close this?
